require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - spec/fixtures/**/*
    - tmp/**/*

Rails:
  Enabled: true

# Style -----------------------------------------------------------------------

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Metrics ---------------------------------------------------------------------

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - config/**/*
    - Rakefile
    - lib/tasks/**/*.rake
    - spec/**/*
    - config/routes.rb

# Layout ----------------------------------------------------------------------

Layout/LineLength:
  Max: 120

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    associations:
      - has_one
      - has_many
      - belongs_to
      - has_and_belongs_to_many
  ExpectedOrder:
      - module_inclusion
      - constants
      - associations
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods

# RSpec -----------------------------------------------------------------------

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# Rails -----------------------------------------------------------------------

Rails/RakeEnvironment:
  Enabled: false
