default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adminframeworks_development

test:
  <<: *default
  database: adminframeworks_test

production:
  <<: *default
  database: adminframeworks_production
  username: adminframeworks
  password: <%= ENV['ADMINFRAMEWORKS_DATABASE_PASSWORD'] %>
